spring:
  application:
    name:jourenal_apk

  data:
      mongodb:
        uri:mongodb+srv://manishkeer530:manishkeer19@manish.dz6nzsm.mongodb.net/journalDb
      database: journalDb

      auto-index-creation: true  

server:
  port: 8081
  servlet:
    context-path: /journal


